### ISSUE TITLE
Can't set music/list for specific actors.

### ISSUE THREAD

**Issue by Nuku** [elizeuangelo/fvtt-module-combat-music-master#1]
I can click 
![image](https://user-images.githubusercontent.com/886729/225506340-7d5b8ea7-3ee0-4c95-9964-c7f561f94f57.png)
And get this
![image](https://user-images.githubusercontent.com/886729/225506369-7945784c-84e5-40c2-b453-c79710b6762e.png)
Dragging music to the window does nothing.
![image](https://user-images.githubusercontent.com/886729/225506417-bd49ffd4-c11e-46aa-968b-e6ad61eda418.png)

**Comment by elizeuangelo** [comment]
This Combat Music button and window seems to be from another module?
To assign tracks to Tokens you need to enter the Token Configuration app.

![image](https://user-images.githubusercontent.com/56921633/225597210-476f8456-5fdd-4e8e-896f-357183cac36a.png)

**Comment by Nuku** [comment]
Oh, shoot! Wow... Where did that other one come from? Sorry for the confusion.
