### ISSUE TITLE
[Feature] Resume combat tracks from last played position

### ISSUE THREAD

**Issue by this-gavagai** [elizeuangelo/fvtt-module-combat-music-master#10]
Thanks for this great module!

I'm testing out Combat Music Master to provide both general combat tracks for NPCs and also personalize hype tracks for Players. As a consequence, the music changes with every player change.

At present, Combat Music Master begins each designated track from the beginning each time a character's turn starts. The results in the same 20-30 seconds of the song over and over again.

Is it possible to have the track resume from where it left off last time? That's the behavior that currently exists in the current module I'm using (Video Game Music), and I'm finding it's something my players miss when we've tested out Combat Music Master.

If this is something that would be considered, I'd be happy to take a stab at it to submit a pull request.

**Comment by elizeuangelo** [comment]
I believe this suggestion is pretty good. I will add a configuration for this behavior.

**Comment by this-gavagai** [comment]
Oh wow, this is incredible! It works great.

One minor detail I noticed: when the combat ends, all of the combat tracks are removed from the playlist, as expected. The exception is the track that was playing when the combat ended, which is paused and left on the playlist. Is that part of the design or an unintended side-effect?

**Comment by elizeuangelo** [comment]
It seems like a bug but Im not being able to reproduce this behavior.

Can you consistentely reproduce it?
Could you show me your specific configurations when doing so?

**Comment by this-gavagai** [comment]
Yes, it happens consistently for me, every time. I just tested on a new world, pf2e, no modules except CMM, and I get the same result. The last track played always stays on the list after combat is ended.

I've tested with a wide range of conditions (default playlists, token-specific playlists, etc.), and it seems consistent. Here's a video demoing settings under the simplest circumstances I could think of. If other info could be helpful, please let me know!


https://github.com/elizeuangelo/fvtt-module-combat-music-master/assets/9303694/a06d9c22-6abe-42ef-b847-15e015de565b

**Comment by elizeuangelo** [comment]
It was a concurrency bug when more than 2 tracks were paused.
Please checkout the latest version v1.4.7 and confirm if its solved

**Comment by this-gavagai** [comment]
Works great! Thanks so much for adding this feature. It has added a really nice polish to our game.
