### ISSUE TITLE
[Feature Request]  Add Track not working in v11

### ISSUE THREAD

**Issue by maplealmond** [elizeuangelo/fvtt-module-combat-music-master#11]
When editing the music for a token, the Add Track option to allow different tracks at different resource levels does not work.

**Test Configuration**

Foundry Virtual Tabletop: Version 11 Stable, 11.305
Game System: pf2e, 5.1.2

**How to Reproduce**

With: Combat Music Master installed
Open character sheet of any character or NPC
Click Token
Click Music
Click "Add Track"

Observed: Nothing happens.  
Expected: A new row is created.

**Comment by elizeuangelo** [comment]
Fixed in next release.
