### ISSUE TITLE
Sometimes, music does not play at all

### ISSUE THREAD

**Issue by BrotherSharper** [elizeuangelo/fvtt-module-combat-music-master#12]
During the first time that a combat starts when a world is first loaded, music plays fine. Then during subsequent combats it starts to get wonky with music just outright not playing at all when combat starts. When using hype tracks, it sometimes goes completely silent on the token's turn and some other times it works correctly.

I used find the culprit and after turning off all other modules except this one, I was able to fully reproduce the issues. (reproduce is used loosely here since it's quite random if this happens)

Here's my settings, steps to reproduce etc.

Playlist:
I have 3 playlists
- "Combat - Normal" (set to default with priority 1, aka starred)
- "Combat - Boss" (used for manual overrides)
- "Combat - Characters" (used for hype tracks)
as follows
![image](https://github.com/elizeuangelo/fvtt-module-combat-music-master/assets/41280723/6e3d7c68-abb9-4ead-a628-93667958d627)

All tracks are set to Loop, no fade has been set

Tokens:
I have 5 tokens
- Player character 1~4, each set with their hype tracks as follows 
![image](https://github.com/elizeuangelo/fvtt-module-combat-music-master/assets/41280723/95c33880-43ed-4af5-90e3-6cdd9caf2cd5)
Priority is 10, turn only is checked, tracked resource is always empty regardless of what I select (because there's no other option atm?)
- Enemy token with no hype track set.

Steps:
- Add all to combat. (note, no player clients are connected, this is just the GM solo testing)
- Roll all at once.
- Begin combat
- Scenario 1 (player character first in order, enemy somewhere in the middle)
       - default track plays over character track (priority 1 beats priority 10?)
       - other charcter's tracks play fine
       - on enemy's turn nothing plays (about 25% of the times, the default track plays)
       - end combat, ambient music resumes
       - start combat again by reading everything
       - enemy always stays silent, character tracks sometimes play, sometimes don't. It's quite random.
- Scenario 2 (enemy first in order)
       - nothing plays (but 25% of the time the default track plays as in scenario 1)
       - subsequent character tracks play fine
       - end combat, ambient music resumes
       - start combat again by reading everything
       - enemy always stays silent, character tracks sometimes play, sometimes don't. It's quite random.

It's a bit hit and miss, but sometimes nothing play at all. Refreshing the world does make everything play, but this is not really feasible during actual play.

There might be something going on with synchronizing what is currently being played?
Perhaps await the track to be fully loaded before firing off the hook that plays it?
I can invite you to the world to test for yourself, this is a bit weird.

**Comment by BrotherSharper** [comment]
I added a bunch of awaits to all the sound.update calls. I was able to get it to work in the character's cases so this is definitely the module needing to await at all the points at which the music is supposed to change.

**Comment by elizeuangelo** [comment]
How are the playlists configured? Could you post a screenshot?
Are your tracks configured to "loop"?

**Comment by BrotherSharper** [comment]
@elizeuangelo here you go!
These are the relevant combat tracks.
![image](https://github.com/elizeuangelo/fvtt-module-combat-music-master/assets/41280723/48f155e3-29cb-488b-8b67-ec1c0bffda09)


They are all set to loop and they are all in OGG format... perhaps that has something to do with it?
I'll try to change them to mp3 and check again.
