### ISSUE TITLE
[Question] Understanding of the priorization

### ISSUE THREAD

**Issue by vt-tom** [elizeuangelo/fvtt-module-combat-music-master#13]
I think i dont fully understand the priorization.
Favorites got prio 1
Combat Tracker got prio 0
Tokens could be set individually.

If the lowest track is chosen, then how could i set the Token prio so it tops the combat tracker if a treshhold is reached?

**Comment by apoapostolov** [comment]
Higher priority overrides lower priority.

**Comment by vt-tom** [comment]
Okay, maybe i configured it wrong. I wanted to start a combat playlist and after the "boss" reaches 50% hp, the other song would be fired. But this configuration doesnt work.  
![grafik](https://github.com/elizeuangelo/fvtt-module-combat-music-master/assets/80099175/7460db49-3b4b-4ea4-956c-00f37e2cddcf)  

Maybe it has something to do with this error, when i start an encounter?  
![grafik](https://github.com/elizeuangelo/fvtt-module-combat-music-master/assets/80099175/e4e427a9-b151-42f9-a73a-5c4c3f18b9e6)

**Comment by vt-tom** [comment]
Nope sorry, forget it. The encounter also occurs without module

**Comment by elizeuangelo** [comment]
Do you have any other tokens with "Active" checked? If so you should provide their configuration as well.

**Comment by vt-tom** [comment]
Nope, only the mother rat.

**Comment by vt-tom** [comment]
Nice, now i understand it. Thanks for the explanation
