### ISSUE TITLE
Combat Master 1.5.1 starts music with initiative rolls, then pauses music when combat starts

### ISSUE THREAD

**Issue by apoapostolov** [elizeuangelo/fvtt-module-combat-music-master#16]
Combat Music Master starts the music when a token rolls for initiative before the first turn BUT when the combat encounter begins and turn one starts it pauses the music.

**Comment by elizeuangelo** [comment]
Fixed on v1.5.2 (b7f9b5bba5599ea8bada74500d5cdcd12b42f3ce)
