### ISSUE TITLE
No Personal Music

### ISSUE THREAD

**Issue by Nuku** [elizeuangelo/fvtt-module-combat-music-master#2]
![image](https://user-images.githubusercontent.com/886729/225638547-d4683ba3-64f6-4e0a-81a8-2c5c86e641a7.png)
I set a song here, but going to their turn on the turn order, still playing generic combat music.

What'd I do wrong? Or is something busted?

**Comment by elizeuangelo** [comment]
It doesn't work like that, the music doesn't play on the token's "turn".

When combat starts, the module checks for the "highest" priority configuration amonst all the combatants, this means a different music than the "standard combat music" can be played for a Boss, for instance. Also, you can set that the music changes when the boss HP gets below 50%, for example, or a victory music when the boss gets to 0%.

**Comment by apoapostolov** [comment]
This mod is made on paid commission, which never included hype tracks as part of the scope. You may want to use Maestro for that, or you could open a commission for this feature with @elizeuangelo whichever works for you.

**Comment by Nuku** [comment]
For sake of curiosity, what would the price we're looking at be?

**Comment by elizeuangelo** [comment]
Call me in discord Magus#9576
