### ISSUE TITLE
Current scene playlist is not pausing, it continues, overlapping

### ISSUE THREAD

**Issue by Old-Man-D** [elizeuangelo/fvtt-module-combat-music-master#21]
I debated writing this up, because I suspect it might be user error on my side.  But what I am experiencing is that when I start combat, I am expecting the scene playlist to stop or pause, so the battle music can take over, but what is happening is that both continue, overlapping.  I have the "pause tracks" option enabled in the settings.

**Comment by elizeuangelo** [comment]
Hm.... "pause ambient sounds" might have a misleading title, it pauses all the music being played in the Playlist Manager. "Ambient Sounds", in the strict sense, are not handled by the playlist manager and should not be paused anyway.
