### ISSUE TITLE
V12 Problem 

### ISSUE THREAD

**Issue by Ginkgo85** [elizeuangelo/fvtt-module-combat-music-master#23]
Will there be an update for the module? Unfortunately I keep getting error messages under V12.

**Comment by elizeuangelo** [comment]
This weekend I will take a look.

**Comment by Ginkgo85** [comment]
yes because the addon always crashes my browser

**Comment by elizeuangelo** [comment]
I updated for better v12 compatibility, please let me know if all issues were addressed.

**Comment by elizeuangelo** [comment]
> > I updated for better v12 compatibility, please let me know if all issues were addressed.
> 
> So far, everything is running smoothly again. I'm so happy that the module is now running again. I hope, of course, that they continue to maintain the module. Because I don't know of any other that has worked so well so far.
> 
> The only thing is that the version is still displayed incorrectly.
> 
> ![image](https://private-user-images.githubusercontent.com/159688644/367221573-a9cf909b-e2e9-4e72-b768-0ef972042a82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzIyNTcsIm5iZiI6MTcyNjIzMTk1NywicGF0aCI6Ii8xNTk2ODg2NDQvMzY3MjIxNTczLWE5Y2Y5MDliLWUyZTktNGU3Mi1iNzY4LTBlZjk3MjA0MmE4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxMjUyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDMxNjNhMDVmN2I1NGJiMzVhYjcyYTJhYWExYWIxOTI2NGIyZjNiNWJlYjhhZGEyZTI1OWU3YTA3NTk3MWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lmxatTIl8_IIZ9XJmyKDQpJi_YnsBj-0weJ62ojK4a8)

I don't understand. What's wrong with the version? The latest version is indeed v1.5.5.

**Comment by Ginkgo85** [comment]
> 
> I don't understand. What's wrong with the version? The latest version is indeed v1.5.5.

It is just not displayed as green yet ;-)

**Comment by elizeuangelo** [comment]
Ok, now it should be green.
