### ISSUE TITLE
STATUS_BREAKPOINT error in newer versions of Chromium 

### ISSUE THREAD

**Issue by silentcatfart** [elizeuangelo/fvtt-module-combat-music-master#24]
Hi there! Somewhere in the last few months Chromium seems to be upset with the module and dumps the browser out to a 
STATUS_BREAKPOINT error. You can't catch anything in the console or the server side to support the problem.
Chrome: Version 128.0.6613.114 (Official Build) (64-bit)
Edge: Version 128.0.2739.54 (Official build) (64-bit)

I had a laptop with an old version of Edge (125) and it seemed to be working fine. 

Also, you can seem to keep reloading the browser and 1 out of 4 times it will load.

I finally disabled this module and it seems to launch Foundry every time. THIS MODULE IS AMAZING BTW!

**Comment by MarkeyMarke** [comment]
Just wanted to bump this; I am also experiencing the same issues. In the mean time I was able to get around it using Brave as my browser.

**Comment by Dadrak** [comment]
Same as above, just a bump, the module is great but it crashes foundry, now i haven't used in firefox

**Comment by elizeuangelo** [comment]
Let me know if these issues persist on the newer version of the module.

**Comment by MarkeyMarke** [comment]
Strangely enough, I am still on v1.5.3 of the mod, and I refreshed the world about 10 times and don't run into the issue any more. Perhaps it was a problem with particular versions of Chrome's browser.
