### ISSUE TITLE
Conflict with PF2e and Monk's Combat Details

### ISSUE THREAD

**Issue by Keatnisher** [elizeuangelo/fvtt-module-combat-music-master#6]
I receive the following error when I change turns in the combat tracker:

![image](https://user-images.githubusercontent.com/26535174/229981429-74f0fba1-e61b-47c3-b896-58870cb71652.png)

It doesn't _always_ occur, but the vast majority of turns are broken, causing the new track to not be played, and sometimes keeping the previous song playing.

Note, this error still occurs even with Monk's Combat Details deactivated. With only PF2e running, here is what I get:

![image](https://user-images.githubusercontent.com/26535174/229981781-f0dd3a46-6d74-4036-a144-5132e98179ad.png)

Let me know if you need any other details. Thanks!

**Comment by Keatnisher** [comment]
I did some more troubleshooting - it turns out these aren't really issues with Monk's Combat Details or PF2e... or at least I think.

I believe there were 2 underlying issues.
1) I didn't have "Turn Only" checked for every token
2) I didn't have a music track selected for every token

Once I fixed both of those 2, the tracks play as expected. However, I would expect that the default music should play under the 2 scenarios affected by the issues above. That is, if a token does not have any music, the default playlist should be playing (tracks that were playing during a "Turn Only" tokens turn _continued_ to play during the turn of a token with no music track). And if a token has "Turn Only" selected, its music should only play during its turn and not leak onto other token's turns.

Also, while messing around with these settings I found that sometimes the tracks leaked onto other tokens. That is, combatant 1 plays combatant 2's music. Combatant 2 plays combatant 3's music, and so on. This may be conflated due to the issues I listed above though - because once I select a Track and "Turn Only" for every token in the combat, this no longer occurs.

Leaving this open so you can handle as you'd like - not sure if the error screenshots I posted or my comments reveal anything important.

**Comment by Keatnisher** [comment]
Sorry another comment - 

It seems like it's just the "Turn Only" button that needs to be selected. The default playlist is playing correctly for tokens with no track selected.

**Comment by elizeuangelo** [comment]
This error seems to be caused because its not finding the music configured for the Token. Could you confirm?

Maybe some token has a music you deleted or moved to another playlist.
