### ISSUE TITLE
Music will not play if certain tokens are included in the battle.

### ISSUE THREAD

**Issue by aba202** [elizeuangelo/fvtt-module-combat-music-master#7]
![image](https://user-images.githubusercontent.com/62639203/234895024-acaff23e-19b6-4c98-bedb-fe4f0c914562.png)

If I place some tokens alone and start a battle, the music won't play.
And if the multiple tokens are in combat, music will not play if the problem token is included.

I didn't have any personal settings on all the tokens.
Also, there is no deleted or moved music file.

Is there a solution to fix this?

**Comment by elizeuangelo** [comment]
What system are you playing?
And what type of actor is the problematic token?

**Comment by elizeuangelo** [comment]
Check out v1.4.4, it should work now.
The issue was caused because those problematic tokens had no "primary attribute", maybe due to the system and actor design.

The module now considers that as a possibility and pretends they have, even if they dont.
