### ISSUE TITLE
V11 Compatibility

### ISSUE THREAD

**Issue by Nuku** [elizeuangelo/fvtt-module-combat-music-master#9]
The module isn't, alas. Is that already being worked on?

**Comment by apoapostolov** [comment]
@Nuku what exactly is the issue
- the module doesn't appear in the world at all (if this is the case, the mod manifest needs to be edited to include version 11. This can now be done in Foundry, right click the mod, choose Edit, change all module version requirements to 11)
- the module appears in the world, but some functionality doesn't work - what exactly?

**Comment by Nuku** [comment]
Ah ha, it appears to basically work. Will open a new issue if something
specific comes up. I thought it was not before, but a new edition came out,
maybe that, no idea. Feel free to close.
